### ISSUE TITLE
Get rid of subscriptions limit, by making check interval depend on it

### ISSUE THREAD

**Issue by imbolc** [ayrat555/el_monitorro#120]
What do you think about increasing / removing the limit this way? E.g. making check interval 2 minutes for 40 subscriptions etc won't require more system resources.

**Comment by ayrat555** [comment]
I'm not sure that it's a viable solution in a long term. Because the limit of 20 is already large enough. 

I think you can deploy your instance of the bot and remove the limit if it's critical for you.

**Comment by imbolc** [comment]
Hmm.. I'd expect an usual RSS user to have at least an order of magnitude more subscriptions. Most of them update about once a month. And people I know read news at most once a day. From this perspective fast delivery doesn't really matter, while the limit is too low.

**Comment by ayrat555** [comment]
Unfortunately, some people need faster updates. 
for example https://t.me/el_monitorro/1713
```
The speed of the bot is the most important thing for me.
```

Also, some users use notification feeds (azure, price deals)

**Comment by imbolc** [comment]
Right, so there's two groups of people, who probably use the bot for different purposes, and this solution came to my mind while thinking on how to satisfy both of them. For those who have a few subscriptions the delivery speed would be the same as it is now, they won't notice the change. But other people can also use the bot as a normal rss reader with hundreds of feeds.

**Comment by ayrat555** [comment]
that's a reasonable suggestion. I'll try to look into it. 

I only work on the bot the weekends. And currently, I have the following plan:

- improve the background processing library that I created recently. This library made it possible to optimize the synchronization speed. https://github.com/ayrat555/fang
- clean up the codebase of the bot. As far as I'm concerned, the code needs some cleaning
- after that, I can work on backlog issues

Btw you're welcome to help. Currently, the bot runs on https://github.com/ayrat555/el_monitorro/pull/114. I'll merge it to master soon

**Comment by imbolc** [comment]
Yes, I guess I can implement it if you're willing to accept the change. So we check a persons feeds each `num_his_feeds / 20` iteration of the sync loop, right?

**Comment by ayrat555** [comment]
@imbolc I'm not sure there a straightforward way to do that yet. Currently feeds are synchronized independently.

Wouldn't it be easier to host the bot for yourself? I know a couple of guys who do that. You can use the cheapest vps or I think you can deploy it on raspberry pi. I'm willing to support you all the way during this process.

**Comment by imbolc** [comment]
Sure, thank you, personally I'm totally fine with the self hosted option. I'll close the issue then.

**Comment by ayrat555** [comment]
Great. If you need some help, please contact me on telegram. @Ayrat555 is my handle
