### ISSUE TITLE
url number

### ISSUE THREAD

**Issue by tapatianbeast** [ayrat555/el_monitorro#169]
Hi terrific job! Could I remove those annoying little numbers next to the urls in the bot_item_description of set_template option?

**Comment by ayrat555** [comment]
@tapatianbeast can you please elaborate?

**Comment by tapatianbeast** [comment]
Yes, when i enable template bot_item_description next to the links there are some numbers like [1], [2] etc..

**Comment by ayrat555** [comment]
@tapatianbeast oh. I understand now I think. 

It means your feeds returns items in HTML format, the bot just removes html
