### ISSUE TITLE
Migrate  telegram api client to async

### ISSUE THREAD

**Issue by ayrat555** [ayrat555/el_monitorro#225]
Currently, we're using a blocking client based on isahc

Since we're already using tokio to process user requests, it would be reasonable to migrate telegram API to async client implemented in Frankenstein - https://github.com/ayrat555/frankenstein/blob/master/src/api/async_telegram_api_impl.rs#L14

**Comment by pxp9** [comment]
We decide not to do it. So we will close this issue.
