### ISSUE TITLE
Feed name changer

### ISSUE THREAD

**Issue by Anknou** [ayrat555/el_monitorro#259]
Hi! wonderful update https://github.com/ayrat555/el_monitorro/pull/243

can u add plz name changer?

{{create_name "blablabla" bot_feed_name}}

**Comment by ayrat555** [comment]
Hello. I think you already can use `blablabla` instead bot_feed_name

**Comment by ayrat555** [comment]
@Anknou Please contract @ayrat555 in Telegram if you won't be able to do it
