### ISSUE TITLE
Feature request: Post into topics

### ISSUE THREAD

**Issue by ikjadoon** [ayrat555/el_monitorro#304]
Would it be possible for el_monitorro bot to post its feeds into a topic, instead of an entire group? [Topics are a new group feature in Telegram](https://telegram.org/blog/topics-in-groups-collectible-usernames) that splits one group into separate topics. Ideally, el_monitorro could post its feeds into just one topic and not into the group itself.

https://codex.so/telegram-bots-in-group-topics

This link above shares some context of how bots can work with topics.

**Comment by ayrat555** [comment]
@ikjadoon hey. can you contract me in telegram (@Ayrat555). I don't have access to topics because it requires a group to have a certain number of users.

If you give me access to a topic so I can experiment, I will add topics support.

**Comment by ikjadoon** [comment]
Hello, @ayrat555! My apologies for my delay. Ah, I understand! I can invite you. However, I _believe_ topics are now open to all users. From a group with two users, I am able to toggle Topics through "Manage Group":

![image](https://user-images.githubusercontent.com/3848795/218898140-b1cab60f-7581-438e-b34e-d97ee0bd0cab.png)

This screenshot is from Telegram v.4.6.2 (x64). [Telegram does seem to confirm the same](https://telegram.org/blog/hidden-media-zero-storage-profile-pics), as of 30 Dec 2022:

![image](https://user-images.githubusercontent.com/3848795/218898556-a04a08cd-caa6-4b9d-93ae-c385e57510e4.png)

However, if I can help invite you, I'm very happy to do so. 🙏

**Comment by ayrat555** [comment]
@ikjadoon I was not aware of it. will try to implement this weekend

**Comment by ikjadoon** [comment]
@ayrat555 no problem at all. I also recently discovered the change. 🙏  Ah, that's amazing! No no, take your time. I don't mean to rush. 

I already sincerely appreciate your efforts and hard work.

**Comment by ayrat555** [comment]
@ikjadoon topics are now supported
