### ISSUE TITLE
Wrong URL for Blogger (blogspot) feed

### ISSUE THREAD

**Issue by rizaumami** [ayrat555/el_monitorro#43]
Using default template, the bot is give a wrong URL to the original article.

Here's an example:
`
/subscribe http://www.sekolahdasar.net/feeds/posts/default
`

And the result is similar to this:
```
Salam Edukasi

Gaji dan Tunjangan PPPK (Pegawai Pemerintah dengan Perjanjian Kerja) Berdasarkan Perpres Nomor 98 Tahun 2020

2020-10-02 18:18:00.004 +00:00

https://www.salamedukasi.com/feeds/7200443794616260064/comments/default
```

When the link is suppossed to target `https://www.salamedukasi.com/2020/10/gaji-dan-tunjangan-pppk-pegawai.html`.

Tried another template as this:
```
/set_global_template bot_feed_name bot_new_line bot_new_line bot_item_name bot_new_line bot_new_line bot_item_description bot_new_line bot_new_line bot_item_link
```

Or, this:
```
/set_global_template bot_feed_name bot_new_line bot_new_line bot_item_name bot_new_line bot_new_line bot_item_description bot_new_line bot_new_line bot_item_link
```

The result is just similar to the default template.

**Comment by ayrat555** [comment]
hey @rizaumami. I deployed a fix, all new items should contain a correct link
