### ISSUE TITLE
Make commands shorter

### ISSUE THREAD

**Issue by angelss197200** [ayrat555/el_monitorro#44]
its tedius to writre /subscribe, /unsubscribe,etc 
instead change it to a short version like /sub ,/uns, /list,etc 
this can show the command's descriptions completly

**Comment by ayrat555** [comment]
> instead change it to a short version like /sub ,/uns, /list,etc

I think it's reasonable. Can you please provide a full list of shortened commands?

**Comment by angelss197200** [comment]
start
sub
uns
list
help
set_time
get_time
set_mod (model)
get_mod 
set_uni_mod (universal model)
get_uni_mod

**Comment by ayrat555** [comment]
@angelss197200 did try auto-completion menu?
<img width="562" alt="Screenshot 2020-11-19 at 23 14 34" src="https://user-images.githubusercontent.com/6567687/99719188-0b32db80-2abd-11eb-90f3-5493b8497e3f.png">

**Comment by ayrat555** [comment]
@angelss197200 I didn't receive a reply from you
