### ISSUE TITLE
Need to add filter option

### ISSUE THREAD

**Issue by telegrambotdev** [ayrat555/el_monitorro#45]
Can you please add filter option ,like if the specific, keywords appears it have to publish,else not.

Also please make it for posting full contents, instead of short Description.we need to get full feed contents,thats why we are using the bot.but almost feed readers are just providing 2 lines of content and then a url for that.so please add an option for getting all the item description

**Comment by ayrat555** [comment]
@telegrambotdev it's possible to add an `item description` using `/set_global_template` and `/set_template` commands

> Can you please add filter option ,like if the specific, keywords appears it have to publish,else not.

What do you mean? can you please describe full use case with the required command, parameters and expected result

**Comment by telegrambotdev** [comment]
> @telegrambotdev it's possible to add an `item description` using `/set_global_template` and `/set_template` commands
> 
> > Can you please add filter option ,like if the specific, keywords appears it have to publish,else not.
> 
> What do you mean? can you please describe full use case with the required command, parameters and expected result

check this site

https://siftrss.com/



The filter works like,it only displays the content which we gave it as a key word.

for example i subscribed  to a general feed,which contains messages like love,fun,joke,angry,news etc.



if i added a filter option for allowed  for a keyword like "love " it only post messages,when the exact filter is detected.

if i added "love" in deny option,all msgs containing that keyword will not publish.This is called `rss filtering`

 can you please add these feature in your code ?

**Comment by ayrat555** [comment]
I'll definitely work on this after some technical tasks I have to resolve first

**Comment by telegrambotdev** [comment]
Thanks

**Comment by ayrat555** [comment]
@telegrambotdev Don't you need this feature anymore? I think it should stay open until it's resolved

**Comment by telegrambotdev** [comment]
> @telegrambotdev Don't you need this feature anymore? I think it should stay open until it's resolved

lol i need that feature.that will be very helpful

**Comment by telegrambotdev** [comment]
> @telegrambotdev Don't you need this feature anymore? I think it should stay open until it's resolved

what about this feature ?

**Comment by ayrat555** [comment]
I'm planning to implement it. It's a good feature to have. But before that, I'll have to fix two higher priority issues

https://github.com/ayrat555/el_monitorro/issues/64
https://github.com/ayrat555/el_monitorro/issues/66
