### ISSUE TITLE
How to post to channels?

### ISSUE THREAD

**Issue by steph9009** [ayrat555/el_monitorro#49]
Hi!

First of all: you're work is REALLY awesome. This is one of the best RSS Telegram bot i've seen so far (and i tried lots of them).

I see you've made a branch to post feeds to channel: i added the bot as admin in a public channel, but i cannot see any option in the private menu!
Please, can you tell me how to do it?

**Comment by ayrat555** [comment]
@steph9009 hey
It doesn't show a menu in channels. Can you please try just running commands. You can ping me on Telegram (@Ayrat555) and I can take a look

I know a couple of people are already using the bot in their channel

**Comment by steph9009** [comment]
solved!
