### ISSUE TITLE
about subscription limit & updates check interval

### ISSUE THREAD

**Issue by telegrambotdev** [ayrat555/el_monitorro#57]
in which file i can change,the  subscription limit &
updates check interval time ?

can you mention the file and line number ?

**Comment by ayrat555** [comment]
I'll add env vars this week so they can be configurable. It's a trivial task

**Comment by telegrambotdev** [comment]
> I'll add env vars this week so they can be configurable. It's a trivial task

Thanks.anyway i dockerised the code for myself😂lol messed up with my 24hrs..

Because the db must be online to continue with `diesel database setup` ..lol that part really messed up bro ..i solved it atlast

**Comment by telegrambotdev** [comment]
> I'll add env vars this week so they can be configurable. It's a trivial task

try to add `filter` option too which i mentioned earlier

**Comment by ayrat555** [comment]
@telegrambotdev 
I added env vars https://github.com/ayrat555/el_monitorro#configuration

> try to add filter option too which I mentioned earlier

Currently, I'm still resolving some technical issues which need more attention. Also,  I can work on the project  only during weekends
