### ISSUE TITLE
"URL is not a feed" error on adding an actual Feed

### ISSUE THREAD

**Issue by UsamaKarim** [ayrat555/el_monitorro#61]
First of all, I want to thank you for your hard work and keep supporting the work ❤️❤️❤️.

I am trying to add a feed of the link [https://propakistani.pk/feed](https://propakistani.pk/feed), the feed is actually an original feed and working fine but I am not able to add it to Bot. It always states that "URL is not a feed". Please fix the bug or tell me the workaround for this issue. Thanks
![Screenshot_2020-11-28-11-51-30-760_org telegram plus](https://user-images.githubusercontent.com/64292174/100495780-ab010100-3170-11eb-8463-cf93ca04ceb2.jpg)

**Comment by ayrat555** [comment]
it's related to the `rss` library https://github.com/rust-syndication/rss/issues/117

Let's see if it will be fixed there

**Comment by ayrat555** [comment]
@UsamaKarim it seems it's a cloudflare protection issue. The feed can be accessed only using a browser.
Please try 
`curl https://propakistani.pk/feed/`. It returns `Checking your browser before accessing propakistani.pk`

I think devs of this site should disable the protection for rss feed 
https://community.cloudflare.com/t/aweber-access-to-rss-feed-being-blocked/55649/2

**Comment by UsamaKarim** [comment]
I don't know, how but a bot can generate feed from this website. The bot link is [@feed_reader_bot](t.me/feed_reader_bot) . I tried many other bots too but no one is able get the feed. I don't like the feed generated from the @feed_reader_bot and I want to use instant view feature just like it's available in your bot.

**Comment by ayrat555** [comment]
I looked into the issue and I think the only way is to contact devs and ask them to add the IP of el monitorro to allowed ips.

**Comment by sp11ff** [comment]
Thank you for such convenient bot, the great replacement for old rss readers :)

having the same issue "URL is not a feed", here is the link: https://andrewlock.net/rss.xml

**Comment by ayrat555** [comment]
@sp11ff It seems something is wrong with this feed. I tried to `curl` a couple of times. It started returning 404. After some time, I managed to add this feed.

Can you please try again?

**Comment by sp11ff** [comment]
@ayrat555 yeah, strange, I was able to add the feed few attempts later
any way, thanks a lot
