### ISSUE TITLE
Embedded item URL into the item name itself 

### ISSUE THREAD

**Issue by heisenberck** [ayrat555/el_monitorro#98]
Hi. i'm using this great bot for reading news. Thanks Ayrat555 - the author for his wonderful work. 

One issue that I have with news and the bot is that the URL of the item is sometimes way too long and complicated. It also get duplicated when telegram generate view for the link itself. 

Therefore, it would be perfect if you could combine/embed the item_link into the item_name so the message will loook much cleaner and nicer.  

Thanks again for all your hard work.

**Comment by ayrat555** [comment]
resolved by https://github.com/ayrat555/el_monitorro/pull/241
